### ISSUE TITLE
No More Sensor Polling!

### ISSUE THREAD

**Issue by MileB** [MileB/kegbot_base#3]
The API we're using, wiringPi, has interrupt driven pins available. We should definitely be using this instead of polling within a busy loop. 

Some design thought will need to be put in to this as we still have to switch through the mux.

Interrupts with moving parts happening in the background will need some design considerations brought up by someone who has taken OS. Atomic operations likely to be a concern.

**Comment by iamyale1994** [comment]
Upon further discussion, interrupt driven design infeasible. Also, current polling rate is too low: 343- 34 Hz from flow meter is 300ms to 30ms period. We need to sample twice of the rate, 30/2 = 15ms for each of the 8 pins of the mux. As a result, polling rate should be 15(ms)/8 = 1875(ns)

**Comment by iamyale1994** [comment]
My fault, it should be 30ms to 3ms, so polling rate should be 1.5(ms) / 8 = 187.5(ns)
